Notebook template + possible menu added
UreshiiSushi/Exponenta-app pull request #5
Opened 2023-11-10 10:13 UTC by olesbychevsky

Notebook Template added
templates for add_note, search_notes, edit_note, delete_note, sort_notes_by_tag added
added possible menu for user

2023-11-11 13:38 UTC, UreshiiSushi requested changes
Огорни цикл While у функцію notes_main(), а меню можна винести у докстрінг у потрійних лапках, щоб друкувати однією командою

2023-11-11 18:06 UTC, olesbychevsky commented
> Огорни цикл While у функцію notes_main(), а меню можна винести у докстрінг у потрійних лапках, щоб друкувати однією командою

Додав + ф-нал з note

2023-11-11 19:03 UTC, UreshiiSushi approved these changes

2023-11-12 15:31 UTC, UreshiiSushi approved these changes

2023-11-12 15:39 UTC, merged